# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4397fea97dea5a66ffd6757a8ceea7dc9d0147d266043a0d0f341b2bf677564860b4c0786e82981747956a58dbf1c438f38820b4dac0b225b65c560b579887cd

test:
  secret_key_base: d45b3257a0aebe3853b1179c1bb9956fcc0d91aea9e8a2db8b43e7c0561dfae9c3dc9af109363a18f97e9a011bea3d96b2dfa854ec499449dae8d8313721900c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
